{"update":{"12.04":[{"package":"python-django","version":"1.3.1-4ubuntu1.3"}],"10.04":[{"package":"python-django","version":"1.1.1-2ubuntu1.6"}],"11.10":[{"version":"1.3-2ubuntu1.4","package":"python-django"}],"12.10":[{"package":"python-django","version":"1.4.1-2ubuntu0.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","threat":["An attacker could exploit this to generate and display arbitrary URLs to users.."],"usn":"USN-1632-1","CVEs":["CVE-2012-4520"],"info":"python-django vulnerability","date":"November 15, 2012"}