{"CVEs":["CVE-2012-3447"],"usn":"USN-1545-1","threat":["A remote attacker could use this to cause a denial of service or possibly gain privileges.."],"info":"nova vulnerability","date":"August 22, 2012","update":{"12.04":[{"package":"python-nova","version":"2012.1+stable~20120612-3ee026e-0ubuntu1.3"}],"11.10":[{"package":"python-nova","version":"2011.3-0ubuntu6.10"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes."}