{"update":{"14.10":[{"package":"python2.7","version":"2.7.8-10ubuntu1.1"},{"version":"2.7.8-10ubuntu1.1","package":"python2.7-minimal"},{"version":"3.4.2-1ubuntu0.1","package":"python3.4"},{"version":"3.4.2-1ubuntu0.1","package":"python3.4-minimal"}],"12.04":[{"version":"2.7.3-0ubuntu3.8","package":"python2.7"},{"package":"python2.7-minimal","version":"2.7.3-0ubuntu3.8"},{"version":"3.2.3-0ubuntu3.7","package":"python3.2"},{"package":"python3.2-minimal","version":"3.2.3-0ubuntu3.7"}],"14.04":[{"package":"python2.7","version":"2.7.6-8ubuntu0.2"},{"version":"2.7.6-8ubuntu0.2","package":"python2.7-minimal"},{"version":"3.4.0-2ubuntu1.1","package":"python3.4"},{"package":"python3.4-minimal","version":"3.4.0-2ubuntu1.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","date":"June 25, 2015","threat":["An attacker could possibly use this issue to read arbitrary memory and expose sensitive information.","A remote attacker could use this issue to expose sensitive information, or possibly execute arbitrary code.","An attacker could possibly use this issue to read arbitrary memory and obtain sensitive information."],"CVEs":["CVE-2013-1752","CVE-2013-1753","CVE-2014-4616","CVE-2014-4650","CVE-2014-7185"],"usn":"USN-2653-1","info":"python2.7, python3.2, python3.4 vulnerabilities"}