{"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","threat":["An attacker could possibly use this issue to cause Python to crash, resulting in denial of service, or possibly execute arbitrary code.."],"update":{"12.10":[{"package":"python2.7","version":"2.7.3-5ubuntu4.4"},{"package":"python2.7-minimal","version":"2.7.3-5ubuntu4.4"},{"package":"python3.2","version":"3.2.3-6ubuntu3.5"},{"version":"3.2.3-6ubuntu3.5","package":"python3.2-minimal"},{"package":"python3.3","version":"3.3.0-1ubuntu0.2"},{"version":"3.3.0-1ubuntu0.2","package":"python3.3-minimal"}],"13.10":[{"package":"python2.7","version":"2.7.5-8ubuntu3.1"},{"version":"2.7.5-8ubuntu3.1","package":"python2.7-minimal"},{"package":"python3.3","version":"3.3.2-7ubuntu3.1"},{"package":"python3.3-minimal","version":"3.3.2-7ubuntu3.1"}],"12.04":[{"package":"python2.7","version":"2.7.3-0ubuntu3.5"},{"version":"2.7.3-0ubuntu3.5","package":"python2.7-minimal"},{"package":"python3.2","version":"3.2.3-0ubuntu3.6"},{"version":"3.2.3-0ubuntu3.6","package":"python3.2-minimal"}],"10.04":[{"version":"2.6.5-1ubuntu6.3","package":"python2.6"},{"version":"2.6.5-1ubuntu6.3","package":"python2.6-minimal"}]},"date":"March 03, 2014","usn":"USN-2125-1","info":"python2.6, python2.7, python3.2, python3.3 vulnerability","CVEs":["CVE-2014-1912"]}