{"date":"February 27, 2012","update":{"10.04":[{"version":"0.7.2-1ubuntu2~0.10.04.1","package":"python-httplib2"}],"11.04":[{"package":"python-httplib2","version":"0.7.2-1ubuntu2~0.11.04.1"},{"package":"python3-httplib2","version":"0.7.2-1ubuntu2~0.11.04.1"}],"11.10":[{"package":"python-httplib2","version":"0.7.2-1ubuntu2~0.11.10.1"},{"version":"0.7.2-1ubuntu2~0.11.10.1","package":"python3-httplib2"}],"10.10":[{"package":"python-httplib2","version":"0.7.2-1ubuntu2~0.10.10.1"},{"package":"python3-httplib2","version":"0.7.2-1ubuntu2~0.10.10.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.\nThis update uses a new upstream release, which includes additional bug\nfixes.","usn":"USN-1375-1","CVEs":[],"threat":["If a remote attacker were able to perform a man-in-the-middle attack, this flaw could be exploited to alter or compromise confidential information in applications that used the httplib2 library.."],"info":"python-httplib2 vulnerability"}