{"update":{"12.10":[{"version":"2012.2.3-0ubuntu2.1","package":"python-nova"}],"13.04":[{"package":"python-nova","version":"1:2013.1-0ubuntu2.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\n  python-nova\n2012.1.3+stable-20130423-e52e6912-0ubuntu1.1\nIn general, a standard system update will make all the necessary changes.","threat":["An authenticated attacker could exploit this to cause a denial of service by creating an image with a large virtual size with little data, then filling the virtual disk.."],"usn":"USN-1831-1","CVEs":["CVE-2013-2096"],"info":"nova vulnerability","date":"May 16, 2013"}